/*
/*1. 解開相依(Constraint)*/
ALTER TABLE TBMUMLOT DROP CONSTRAINT [Key_6_7]

/*2. 改變欄位型態*/
ALTER TABLE TBMUMLOT ALTER COLUMN area NVARCHAR(20) NOT NULL

/*3. area欄位加入DEFAULT*/
ALTER TABLE TBMUMLOT ADD CONSTRAINT [Key_6_7] DEFAULT('') FOR [area]
*/

--ALTER TABLE TBMUMLOT MODIFY COLUMN area NVARCHAR(20) NOT NULL
/*
/*查詢DG資料庫中所有索引*/
SELECT DISTINCT SC.name AS Schema_Name, 
                      O.name AS Table_Name, 
				      I.name AS Index_Name, 
				      I.type_desc AS Index_Type
       FROM sys.indexes I
      INNER JOIN sys.objects O ON I.object_id = O.object_id
      INNER JOIN sys.schemas SC ON O.schema_id = SC.schema_id
	  WHERE I.name IS NOT NULL AND O.type = 'U' AND (I.name = 'PK_TBMUMLOA_21' OR LEFT(I.name, 2) <> 'PK')
*/

/*刪除索引*/
/*
DROP INDEX Key_6_7 ON TBMUMLOT
DROP INDEX index_paltno ON TBMUTRXH
*/
/*
/*刪除索引*/
DROP INDEX TRXR_1_2_3_4_5 ON TBMUTRXR
DROP INDEX machno ON TBMUWORL
DROP INDEX IX_TBMUTRXY ON TBMUTRXY
DROP INDEX index_date ON TBSMORDA
DROP INDEX PK_TBMUMLOA_21 ON TBMUMLOA
DROP INDEX TBSMORDC_1 ON TBSMORDC
--DROP INDEX pk_dtproperties ON dtproperties
DROP INDEX index_flow ON TBQCODCK
*/
/*
SELECT * FROM sys.indexes WHERE index_id = '2' AND is_unique = '0'
*/

/*
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'TBMUMLOT'
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'TBMUTRXH'
*/

/*建立索引*/
/*CREATE INDEX Key_6_7 ON TBMUMLOT*/

CREATE INDEX PK_TBMUMLOA_21 ON TBMUMLOA ()
CREATE INDEX Key_6_7 ON TBMUMLOT (area)
CREATE INDEX index_paltno ON TBMUTRXH (paltno)
CREATE INDEX TRXR_1_2_3_4_5 ON TBMUTRXR ()
CREATE INDEX IX_TBMUTRXY ON TBMUTRXY ()
CREATE INDEX machno ON TBMUWORL ()
CREATE INDEX index_flow ON TBQCODCK
CREATE INDEX index_date ON TBSMORDA
CREATE INDEX TBSMORDC_1 ON TBSMORDC